server:
  port: 8088
  error:
    path: /error

# debug打开可以看到启动时哪些自动配置生效或者不生效
debug: false


#字面量：date、boolean、string、number、null

#对象：键值对的集合。map、hash、set、object

#数组：一组按次序排列的值。array、list、queue

person:
  name: mcdull
  age: 18

spring:
  mvc:
    # 修改静态资源访问的路径前缀，
    # 可以用来区分静态资源访问路径和普通的接口访问路径。
    static-path-pattern: /ccc/**

    # 内容协商相关
    contentnegotiation:
      # 内容协商支持在请求参数中
      # 访问地址中加上参数format=xml，例如 http://localhost:8088/person/get?format=xml
      favor-parameter: true
      # 支持请求参数format中用自定义的媒体类型，值是map
      # 访问地址：http://localhost:8088/person/get?format=x-mcdull
      media-types: {x-mcdull: "application/x-mcdull", "x-json": application/json}

  resources:
    # 修改服务器端静态资源存放的路径
    static-locations: [classpath:/pic/]
# 访问地址 http://localhost:8088/ccc/gg.jpg


